import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
  version: 23,
  tables: [
    tableSchema({
      name: 'rooms',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'roomType', type: 'number' },
        { name: 'typeOfGroup', type: 'number' },
        { name: 'rid', type: 'string' },
        { name: 'topic', type: 'string', isOptional: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'image', type: 'string', isOptional: true },
        { name: 'ownerId', type: 'string', isOptional: true },
        { name: 'tags', type: 'string', isOptional: true },
        { name: 'participantCount', type: 'string', isOptional: true },
        { name: 'lastMessage', type: 'string', isOptional: true },
        { name: 'participantInfo', type: 'string', isOptional: true },
        { name: 'hasUnreadMessage', type: 'boolean', isOptional: true },
        { name: 'leaveGroupHistories', type: 'boolean', isOptional: true },
        { name: 'e2e_key_id', type: 'string', isOptional: true },
        { name: 'unreadCount', type: 'number', isOptional: true },
        { name: 'isFavorite', type: 'boolean', isOptional: true },
        { name: 'notifyStatus', type: 'boolean', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'messages',
      columns: [
        { name: 'message', type: 'string', isOptional: true },
        { name: 'messageContentRaw', type: 'string', isOptional: true },
        { name: 'mId', type: 'string', isIndexed: true },
        { name: 'rId', type: 'string', isIndexed: true },
        { name: 'timeSend', type: 'string' },
        { name: 'senderId', type: 'string' },
        { name: 'userId', type: 'string' },
        { name: 'mentionsIds', type: 'boolean', isOptional: true },
        { name: 'avatar', type: 'string', isOptional: true },
        { name: 'receiperId', type: 'string', isOptional: true },
        { name: 'attachments', type: 'string', isOptional: true },
        { name: 'type', type: 'number', isOptional: true },
        { name: 'revokeEnum', type: 'number' },
        { name: 'isDeleted', type: 'boolean', isOptional: true },
        { name: 'isPinedById', type: 'string', isOptional: true },
        { name: 'isEdited', type: 'boolean', isOptional: true },
        { name: 'isSave', type: 'boolean', isOptional: true },
        { name: 'reactions', type: 'string', isOptional: true },
        { name: 'isPined', type: 'boolean', isOptional: true },
        { name: 'countValue', type: 'number', isOptional: true },
        { name: 'lastEditTime', type: 'string', isOptional: true },
        { name: 'emoji', type: 'string', isOptional: true },
        { name: 'username', type: 'string', isOptional: true },
        { name: 'lastPinedTime', type: 'string', isOptional: true },
      ],
    }),
    // tableSchema({
    //   name: 'threads',
    //   columns: [
    //     { name: 'msg', type: 'string', isOptional: true },
    //     { name: 't', type: 'string', isOptional: true },
    //     { name: 'rid', type: 'string', isIndexed: true },
    //     { name: '_updated_at', type: 'number' },
    //     { name: 'ts', type: 'number' },
    //     { name: 'u', type: 'string' },
    //     { name: 'alias', type: 'string', isOptional: true },
    //     { name: 'parse_urls', type: 'string', isOptional: true },
    //     { name: 'groupable', type: 'boolean', isOptional: true },
    //     { name: 'avatar', type: 'string', isOptional: true },
    //     { name: 'emoji', type: 'string', isOptional: true },
    //     { name: 'attachments', type: 'string', isOptional: true },
    //     { name: 'urls', type: 'string', isOptional: true },
    //     { name: 'status', type: 'number', isOptional: true },
    //     { name: 'pinned', type: 'boolean', isOptional: true },
    //     { name: 'starred', type: 'boolean', isOptional: true },
    //     { name: 'edited_by', type: 'string', isOptional: true },
    //     { name: 'reactions', type: 'string', isOptional: true },
    //     { name: 'role', type: 'string', isOptional: true },
    //     { name: 'drid', type: 'string', isOptional: true },
    //     { name: 'dcount', type: 'number', isOptional: true },
    //     { name: 'dlm', type: 'number', isOptional: true },
    //     { name: 'tmid', type: 'string', isOptional: true },
    //     { name: 'tcount', type: 'number', isOptional: true },
    //     { name: 'tlm', type: 'number', isOptional: true },
    //     { name: 'replies', type: 'string', isOptional: true },
    //     { name: 'mentions', type: 'string', isOptional: true },
    //     { name: 'channels', type: 'string', isOptional: true },
    //     { name: 'unread', type: 'boolean', isOptional: true },
    //     { name: 'auto_translate', type: 'boolean', isOptional: true },
    //     { name: 'translations', type: 'string', isOptional: true },
    //     { name: 'e2e', type: 'string', isOptional: true },
    //     { name: 'draft_message', type: 'string', isOptional: true },
    //   ],
    // }),
    // tableSchema({
    //   name: 'thread_messages',
    //   columns: [
    //     { name: 'msg', type: 'string', isOptional: true },
    //     { name: 't', type: 'string', isOptional: true },
    //     { name: 'rid', type: 'string', isIndexed: true },
    //     { name: 'subscription_id', type: 'string', isIndexed: true },
    //     { name: '_updated_at', type: 'number' },
    //     { name: 'ts', type: 'number' },
    //     { name: 'u', type: 'string' },
    //     { name: 'alias', type: 'string', isOptional: true },
    //     { name: 'parse_urls', type: 'string', isOptional: true },
    //     { name: 'groupable', type: 'boolean', isOptional: true },
    //     { name: 'avatar', type: 'string', isOptional: true },
    //     { name: 'emoji', type: 'string', isOptional: true },
    //     { name: 'attachments', type: 'string', isOptional: true },
    //     { name: 'urls', type: 'string', isOptional: true },
    //     { name: 'status', type: 'number', isOptional: true },
    //     { name: 'pinned', type: 'boolean', isOptional: true },
    //     { name: 'starred', type: 'boolean', isOptional: true },
    //     { name: 'edited_by', type: 'string', isOptional: true },
    //     { name: 'reactions', type: 'string', isOptional: true },
    //     { name: 'role', type: 'string', isOptional: true },
    //     { name: 'drid', type: 'string', isOptional: true },
    //     { name: 'dcount', type: 'number', isOptional: true },
    //     { name: 'dlm', type: 'number', isOptional: true },
    //     { name: 'tcount', type: 'number', isOptional: true },
    //     { name: 'tlm', type: 'number', isOptional: true },
    //     { name: 'replies', type: 'string', isOptional: true },
    //     { name: 'mentions', type: 'string', isOptional: true },
    //     { name: 'channels', type: 'string', isOptional: true },
    //     { name: 'unread', type: 'boolean', isOptional: true },
    //     { name: 'auto_translate', type: 'boolean', isOptional: true },
    //     { name: 'translations', type: 'string', isOptional: true },
    //     { name: 'e2e', type: 'string', isOptional: true },
    //   ],
    // }),
    tableSchema({
      name: 'custom_emojis',
      columns: [
        { name: 'name', type: 'string', isOptional: true },
        { name: 'aliases', type: 'string', isOptional: true },
        { name: 'extension', type: 'string' },
        { name: '_updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'frequently_used_emojis',
      columns: [
        { name: 'content', type: 'string', isOptional: true },
        { name: 'extension', type: 'string', isOptional: true },
        { name: 'is_custom', type: 'boolean' },
        { name: 'count', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'uploads',
      columns: [
        { name: 'path', type: 'string', isOptional: true },
        { name: 'rid', type: 'string', isIndexed: true },
        { name: 'name', type: 'string', isOptional: true },
        { name: 'tmid', type: 'string', isOptional: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'size', type: 'number' },
        { name: 'type', type: 'string', isOptional: true },
        { name: 'store', type: 'string', isOptional: true },
        { name: 'progress', type: 'number' },
        { name: 'error', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'settings',
      columns: [
        { name: 'value_as_string', type: 'string', isOptional: true },
        { name: 'value_as_boolean', type: 'boolean', isOptional: true },
        { name: 'value_as_number', type: 'number', isOptional: true },
        { name: 'value_as_array', type: 'string', isOptional: true },
        { name: '_updated_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'roles',
      columns: [{ name: 'description', type: 'string', isOptional: true }],
    }),
    tableSchema({
      name: 'permissions',
      columns: [
        { name: 'roles', type: 'string' },
        { name: '_updated_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'slash_commands',
      columns: [
        { name: 'params', type: 'string', isOptional: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'client_only', type: 'boolean', isOptional: true },
        { name: 'provides_preview', type: 'boolean', isOptional: true },
        { name: 'app_id', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'users',
      columns: [
        { name: '_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string', isOptional: true },
        { name: 'username', type: 'string', isIndexed: true },
        { name: 'avatar_etag', type: 'string', isOptional: true },
      ],
    }),
  ],
});
